version: 2
updates:
  # Enable dependency updates for Python
  - package-ecosystem: "pip"
    # Path to the directory containing the pyproject.toml
    directory: "/part-14-send-email-in-background/backend/app/pyproject.toml"
    # Check for updates daily, which is the most frequent option available
    schedule:
      interval: "daily"
    # Optional: Limit the number of open pull requests Dependabot will create
    open-pull-requests-limit: 10
